version: '3'

services:
  app:
    build: .
    volumes:
      - .:/php
      - ~/.composer/cache:/composer/cache
    environment:
      COMPOSER_CACHE_DIR: '/composer/cache'
      PHP_DISPLAY_ERRORS: 1
